### ISSUE TITLE
How do I compile? Can I change it to a local demo? The following is a compilation error

### ISSUE THREAD

**Issue by zorro0799** [smittytone/FontWrangler#1]
Build input file cannot be found: '/Users/smitty/OneDrive/Programming/mnu/Secrets.swift'
/Volumes/BackupPlus/mac/developer/ios/swift/FontWrangler-master/FontWrangler/FontWrangler/FeedbackViewController.swift:120:48: Cannot find 'MNU_SECRETS' in scope

**Comment by smittytone** [comment]
This repo contains just source code, not data, fonts or graphics. You'll have to add these yourself, replacing the file references to files of your own.

**Comment by zorro0799** [comment]
Thank You
