### ISSUE TITLE
Monospace fonts for developers

### ISSUE THREAD

**Issue by cleverdevil** [smittytone/FontWrangler#8]
Hello there! I am a developer and I found your app here on GitHub. I was looking to create an app very similar to this one, but focused on fonts designed for programmers. Specifically, the monospace "nerd fonts" available here:

    https://www.nerdfonts.com/

These fonts contain embedded icon glyphs, programming ligatures, and other features that are highly desirable for a narrow set of users. I am currently installing some of these fonts manually using the old “VPN profile” trick that many font managers on iOS use, but it’s a big pain and very off putting for most users.

I am writing you here because I’d like to know if you’d be open to either adding a subset of the Nerd Fonts referenced above to Fontismo, or allowing me to use the source code here to publish an app like Fontismo but targeted at people looking for monospace programmer fonts. You've done a lovely job on this app and I think its the ideal foundation for font management done the *right way*.

(Sorry to open this as an issue, but I couldn't find a better way to contact you.)

**Comment by smittytone** [comment]
I'll look into this. Including some/all of these fonts is doable, provided the fonts are suitably licensed.

**Comment by cleverdevil** [comment]
Great news! Thanks for being open to the idea. I really think it will be a popular feature for techie users. Looking forward to finally having a good option here.

**Comment by smittytone** [comment]
I'm getting to the end of work on a Fontismo update I've been preparing, so now's a good time to think about how to make this happen. Do you have suggestions for a handful of Nerd Fonts that I might include?

**Comment by cleverdevil** [comment]
Nice. There are probably too many fonts in total to add, so the subset from nerdfonts.com that I would recommend are:

- CaskaydiaCove
- FiraCode
- Hack
- Inconsolata
- JetBrainsMono
- Monaspice
- Ubuntu
- UbuntuSans

**Comment by smittytone** [comment]
Fonstismo 2.0.0 released via App Store, with some of these faces added.
